[build]
  command = "NITRO_PRESET=static npm run generate"
  publish = ".output/public"

[build.environment]
  NETLIFY_SKIP_NUXT_PLUGIN = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
